version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: thalassa
      POSTGRES_PASSWORD: dev
volumes:
  postgres:
    driver: local